### ISSUE TITLE
Wishlist?

### ISSUE THREAD

**Issue by immigrantsheep** [Tidwell/nodeSteam#12]
Hi,

are wishlists supported or is there any way to retrieve them / integrate them in the current code?

Tnx!

**Comment by Tidwell** [comment]
Valve's API doesn't currently support getting a user's wishlists.  A quick search shows a lot of requests for it, but no official response from Valve.  I have seen an example in the python wrapper library that uses scraping to accomplish this.  I don't think we want to add it to this library as we only want to focus on the official API methods valve has provided.

Here is a link to an example in python, this would be relatively trivial to replicate with node's request and cheerio modules: https://github.com/naiyt/steamapiwrapper/blob/master/steamapiwrapper/Users.py#L170

**Comment by mattclaw** [comment]
Another helpful link for those that land on this issue:

https://lab.xpaw.me/steam_api_documentation.html#IPlayerService

Regarding scraping, you might need a headless browser with JS support for long wishlists.  I have 88 games in my wishlist, and they're all present in the response HTML on initial load.  However, a long wishlist might have a portion of the list lazy loaded (or on a second page entirelym in which case request+cheerio should be sufficient).

**Comment by immigrantsheep** [comment]
Thanks a lot guys!
