### ISSUE TITLE
Steam API v0001 gives a 404

### ISSUE THREAD

**Issue by damoncasale** [Tidwell/nodeSteam#24]
Attempting to call s.getSchema gives a 404.  I traced the issue to the version in the requested path.  Changing the version to v0002 works.

**Comment by Tidwell** [comment]
Do you have some example code for this failing, I just tested locally and this seemed to work okay:

```js
const Steam = require('steam-web');
const APIKEY = require('./key.js');

const s = new Steam({
  apiKey: APIKEY,
  format: 'json'
});

s.getSchema({
  gameid: 440,
  callback: (err, data) => {
    if (err) {
      throw new Error(err);
    }
    console.log(data);
  }
});
```

**Comment by Tidwell** [comment]
It might be related to which gameid, perhaps different games are only supported on v2 - were you using tf2 (440) or another game?

**Comment by damoncasale** [comment]
I was using CS:GO (730).

**Comment by Tidwell** [comment]
Confirmed, 730 only works with v2 and 440 only works with v1.  I'll have to see if the other IEconItems methods behave the same way.  Probably have to do some kind of mapping, or default to requesting from v1 and if it fails make the request to v2.

**Comment by damoncasale** [comment]
Might I suggest making the version number a parameter as well, with a default of v0001?

**Comment by Tidwell** [comment]
Yea, that's probably the best stop-gap to get a fix out quickly, I hate the idea of making double requests or mapping, and without a breaking change that would necessitate a major version bump.

I'll update all the methods to accept an optional version config and to use their default (theres v0001, v0002, v1, and v2 so have to do it case-by-case).

This will at least allow implementors to use the methods if they find the default doesn't work.

**Comment by Tidwell** [comment]
0.6.0 has been published to NPM with support for the .apiVersion config property for all methods.  This should resolve the issue.
