### ISSUE TITLE
getPlayerItems() isn't working.

### ISSUE THREAD

**Issue by VamOSGS** [Tidwell/nodeSteam#27]
![image](https://user-images.githubusercontent.com/26979773/35766231-42d9dc40-08ed-11e8-857d-b48c1ab2d500.png)
![image](https://user-images.githubusercontent.com/26979773/35766232-53a3844a-08ed-11e8-997c-e74329fca0bb.png)

**Comment by Tidwell** [comment]
Confirmed.  This still works fine with TF2.  It looks like valve has disabled it entirely for CS.

Did some digging, and there is a reddit thread from a little while back that shows this:

https://www.reddit.com/r/SteamBot/comments/5ztiv6/psa_api_method_shutdown_ieconitems/

**Comment by Tidwell** [comment]
Updated and deployed 0.7.0 so that all 4xx errors get handled as error callbacks.  I imagine valve's choice had a lot to do with the betting/gambling sites, shame they had to disable it for everyone.

**Comment by VamOSGS** [comment]
Okay thank you!
