### ISSUE TITLE
JSON response invalid, your API key is most likely wrong

### ISSUE THREAD

**Issue by alexrohs01** [Tidwell/nodeSteam#33]
Since today, I always get this error:
`JSON response invalid, your API key is most likely wrong`

It worked before that for a long time. I refreshed my API Key and inserted a new one, but that didnt worked. 
Thats the code I use:

`steamAPI.getPlayerSummaries({
		steamids:steamID,
		callback: function(err,data){
			console.log(err,data,steamID)
		}
	})			`

**Comment by mattclaw** [comment]
Have you spent any time debugging this issue? Can you tell us what the response is you're getting from the server? If you're familiar with debugging tools you could set breakpoints and step through the code, but you could also just do it the simple way and add some `console.log`s within the nodesteam library in your `node_modules/`.

**Comment by alexrohs01** [comment]
Ah thanks. I ran into the "To Many requests" from steam. Kinda strange, I have the error for about 2 days now,
