### ISSUE TITLE
Botlogon

### ISSUE THREAD

**Issue by OfficialJoe** [Tidwell/nodeSteam#6]
The issue I have is that I need to fill in a Username or Password actually I haven't that information of any user so how can I make that that I works with "Login with steam" steam authenticator

**Comment by Tidwell** [comment]
This library only provides access to public information available via the web api and does not allow interaction with a user's account.  If you want to get the users backpack or game information, you can use the user's steamId that you get from the steam oauth flow.  If you are looking to do interactions with the users account, you will want to take a look at https://github.com/seishun/node-steam - that library provides low level access.
